import "./globals.css";
import {ReactNode} from "react";
import type {Metadata} from "next";
import {getServerSession} from "next-auth";
import Navbar from "@/components/navbar";
import {Toaster} from "@/components/ui/toaster";
import Providers from "@/provider/providers";

import { ABeeZee } from 'next/font/google'
import {authOptions} from "@/utils/authOptions";

const roboto = ABeeZee({
    weight: '400',
    subsets: ['latin'],
})


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: ReactNode;
}>) {
    const session = await getServerSession(authOptions);
    return (
        <html lang="en">
        <body
            className={`${roboto.className} antialiased bg-secondary text-foreground flex flex-col`}
        >
        <Providers>
            <Navbar session={session}/>
            {children}
            <Toaster/>
        </Providers>
        </body>
        </html>
    );
}
